### ISSUE TITLE
Wiring Diagram + Pedal pots trick

### ISSUE THREAD

**Issue by mcrustk2** [akakikuumeri/pipechair-cockpit#3]
Hey there! I left a comment (Jimbos SimRigs) on the video (https://www.youtube.com/watch?v=8db8fcycaJI) a while back.

One thing that would be good for the repo is a really simple basic wiring diagram and you also mentioned using a special trick with the pedals where you have wired two pots to oppose each other, so even if you push down on both at the same time and manage to bend them somewhat, the values cancel out. The resistor is a part of that. Im keen to learn a little more of how this hangs together and replicate, any info would be grately appreciated.

This is a fantastic project and I too will be printing this over the coming weeks, im just not as confident with the electronics side without more detail. Its absolutely fantastic though! Maybe you should setup a small discord group for this project, im sure there would be a few of us chatting.

All the best,

James.

**Comment by akakikuumeri** [comment]
Hi, I'm sorry I forgot to do it earlier, I added a photo and a diagram. The resistors are optional, it is very unlikely the pots would ever go to their far end at the same time once it is all installed.
